### PR TITLE
Support non-Arduino devices, eg Particle boards

### PR DESCRIPTION
**Pull request by samyk**
Thank you for creating a pull request to contribute to Adafruit's GitHub code!
Before you open the request please review the following guidelines and tips to
help it be more easily integrated:

- **Describe the scope of your change--i.e. what the change does and what parts
  of the code were modified.**  This will help us understand any risks of integrating
  the code.
Simply does not require the `ARDUINO` define; all existing functionality is unchanged.

- **Describe any known limitations with your change.**  For example if the change
  doesn't apply to a supported platform of the library please mention it.
If a non-Arduino platform doesn't support Wire.write(), this may have an issue, though I believe this is generally supported among MCU platforms with Arduino style cores.

- **Please run any tests or examples that can exercise your modified code.**  We
  strive to not break users of the code and running tests/examples helps with this
  process.

Thank you again for contributing!  We will try to test and integrate the change
as soon as we can, but be aware we have many GitHub repositories to manage and
can't immediately respond to every request.  There is no need to bump or check in
on a pull request (it will clutter the discussion of the request).

Also don't be worried if the request is closed or not integrated--sometimes the
priorities of Adafruit's GitHub code (education, ease of use) might not match the
priorities of the pull request.  Don't fret, the open source community thrives on
forks and GitHub makes it easy to keep your changes in a forked repo.

After reviewing the guidelines above you can delete this text from the pull request.

### CODE REVIEW

**Comment by ladyada** [comment]
oof where did you even get one of these?  :)

what we should really do is remove all the Wire stuff and use Adafruit_BusIO which makes it cross-platform with every arduino library. i could do that but i dont have a sensor to test it with...

**Comment by samyk** [comment]
I know a guy who knows a gal.

Updated to use Adafruit_BusIO! Is there a proper method (git submodule, library.properties, something else?) to allow the CI to use the external lib, or any other best practices when requiring another library?

Thanks!

**Comment by samyk** [comment]
PS, example program tested on 3.3V Nano and Particle Photon in sunny LA.

```
Temperature = 25.30 *C
Pressure = 100473 Pa
Altitude = 71.18 meters
Pressure at sealevel (calculated) = 100475 Pa
Real altitude = 85.37 meters
```

**Comment by ladyada** [comment]
woah! incredible speed - yes hold on ill make the adjustments, i think i can push to the PR branch

**Comment by ladyada** [comment]
ok pleae try
https://github.com/adafruit/Adafruit-BMP085-Library/pull/28

**Comment by ladyada** [comment]
or, even better, https://github.com/adafruit/Adafruit-BMP085-Library/pull/29 which lets you use any I2C port

**Comment by samyk** [comment]
Tested #29, it works!

**Comment by ladyada** [comment]
huzza!

**Pull request merged**
